main = ".worker-next/index.mjs"
name = "my-app"
compatibility_date = "2024-11-16"
compatibility_flags = ["nodejs_compat"]
experimental_assets = { directory = ".worker-next/assets", binding = "ASSETS" }